/*
	This file was generated by Razor\Menu\MenuTogglePlugins.cs and contains custom plugin toggle states.
*/

namespace Turbo.Plugins.User
{
	using Turbo.Plugins.Default;
	using Turbo.Plugins.Razor.Util;

	public class DefaultPluginEnablerOrDisabler : BasePlugin, ICustomizer
	{
		public DefaultPluginEnablerOrDisabler() { Enabled = true; Order = int.MaxValue; }

		public void Customize()
		{
			Hud.TryTogglePlugin("Default.AttributeLabelListPlugin", false);
			Hud.TryTogglePlugin("Default.BannerPlugin", false);
			Hud.TryTogglePlugin("Default.BloodShardPlugin", true);
			Hud.TryTogglePlugin("Default.BountyTablePlugin", false);
			Hud.TryTogglePlugin("Default.CheatDeathBuffFeederPlugin", true);
			Hud.TryTogglePlugin("Default.ChestPlugin", true);
			Hud.TryTogglePlugin("Default.ClickableChestGizmoPlugin", false);
			Hud.TryTogglePlugin("Default.ConventionOfElementsBuffListPlugin", true);
			Hud.TryTogglePlugin("Default.CooldownSoundPlayerPlugin", false);
			Hud.TryTogglePlugin("Default.CosmeticItemsPlugin", true);
			Hud.TryTogglePlugin("Default.CursedEventPlugin", true);
			Hud.TryTogglePlugin("Default.DamageBonusPlugin", false);
			Hud.TryTogglePlugin("Default.DangerousMonsterPlugin", false);
			Hud.TryTogglePlugin("Default.DeadBodyPlugin", false);
			Hud.TryTogglePlugin("Default.DebugPlugin", false);
			Hud.TryTogglePlugin("Default.EliteMonsterAffixPlugin", true);
			Hud.TryTogglePlugin("Default.EliteMonsterSkillPlugin", true);
			Hud.TryTogglePlugin("Default.ExperienceOverBarPlugin", false);
			Hud.TryTogglePlugin("Default.ExplosiveMonsterPlugin", true);
			Hud.TryTogglePlugin("Default.GameInfoPlugin", true);
			Hud.TryTogglePlugin("Default.GlobePlugin", true);
			Hud.TryTogglePlugin("Default.GoblinPlugin", true);
			Hud.TryTogglePlugin("Default.GroundLabelDecoratorPainterPlugin", true);
			Hud.TryTogglePlugin("Default.HeadStonePlugin", true);
			Hud.TryTogglePlugin("Default.HoveredItemInfoPlugin", true);
			Hud.TryTogglePlugin("Default.InventoryAndStashPlugin", true);
			Hud.TryTogglePlugin("Default.InventoryFreeSpacePlugin", true);
			Hud.TryTogglePlugin("Default.InventoryKanaiCubedItemsPlugin", false);
			Hud.TryTogglePlugin("Default.InventoryMaterialCountPlugin", true);
			Hud.TryTogglePlugin("Default.ItemsPlugin", true);
			Hud.TryTogglePlugin("Default.MarkerPlugin", true);
			Hud.TryTogglePlugin("Default.MiniMapLeftBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.MiniMapRightBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.MonsterPackPlugin", false);
			Hud.TryTogglePlugin("Default.MonsterRiftProgressionColoringPlugin", true);
			Hud.TryTogglePlugin("Default.MultiplayerExperienceRangePlugin", false);
			Hud.TryTogglePlugin("Default.NetworkLatencyPlugin", false);
			Hud.TryTogglePlugin("Default.NotifyAtRiftPercentagePlugin", false);
			Hud.TryTogglePlugin("Default.OculusPlugin", true);
			Hud.TryTogglePlugin("Default.OriginalHealthPotionSkillPlugin", false);
			Hud.TryTogglePlugin("Default.OriginalSkillBarPlugin", false);
			Hud.TryTogglePlugin("Default.OtherPlayersPlugin", true);
			Hud.TryTogglePlugin("Default.ParagonCapturePlugin", false);
			Hud.TryTogglePlugin("Default.PickupRangePlugin", true);
			Hud.TryTogglePlugin("Default.PlayerBottomBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.PlayerLeftBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.PlayerRightBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.PlayerSkillPlugin", false);
			Hud.TryTogglePlugin("Default.PlayerTopBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.PortalPlugin", true);
			Hud.TryTogglePlugin("Default.PortraitBottomStatsPlugin", true);
			Hud.TryTogglePlugin("Default.RackPlugin", false);
			Hud.TryTogglePlugin("Default.ResourceOverGlobePlugin", true);
			Hud.TryTogglePlugin("Default.RiftPlugin", true);
			Hud.TryTogglePlugin("Default.SceneHintPlugin", true);
			Hud.TryTogglePlugin("Default.SkillRangeHelperPlugin", false);
			Hud.TryTogglePlugin("Default.StandardMonsterPlugin", true);
			Hud.TryTogglePlugin("Default.StashPreviewPlugin", false);
			Hud.TryTogglePlugin("Default.StashUsedSpacePlugin", true);
			Hud.TryTogglePlugin("Default.TopExperienceStatistics", false);
			Hud.TryTogglePlugin("Default.TopLeftBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.TopMonsterHealthBarPlugin", false);
			Hud.TryTogglePlugin("Default.TopRightBuffListPlugin", false);
			Hud.TryTogglePlugin("Default.UiHiddenPlayerSkillBarPlugin", true);
			Hud.TryTogglePlugin("Default.WaypointQuestsPlugin", true);
			Hud.TryTogglePlugin("Enhanced.UiElementClickBlockerPlugin", true);

		}
	}
}