/*
	This file was generated by Razor\Menu\MenuTogglePlugins.cs and contains custom plugin toggle states.
*/

namespace Turbo.Plugins.User
{
	using Turbo.Plugins.Default;
	using Turbo.Plugins.Razor.Util;

	public class CustomPluginEnablerOrDisabler : BasePlugin, ICustomizer
	{
		public CustomPluginEnablerOrDisabler() { Enabled = true; Order = int.MaxValue; }

		public void Customize()
		{
			Hud.TryTogglePlugin("Custom.DoorsPlugin", true);
			Hud.TryTogglePlugin("Custom.MinimapCursorPlugin", true);
			Hud.TryTogglePlugin("Custom.MonsterCirclePlugin", true);
			Hud.TryTogglePlugin("Custom.PartyCooldownsPlugin", true);
			Hud.TryTogglePlugin("Custom.RatrunsPlugin", true);
			Hud.TryTogglePlugin("Custom.RiftOrbPlugin", true);
			Hud.TryTogglePlugin("Custom.ShockTowerPlugin", false);
			Hud.TryTogglePlugin("DAV.DAV_Extend_OtherPlugin", true);
			Hud.TryTogglePlugin("DAV.DAV_NecroPetPlugin", true);
			Hud.TryTogglePlugin("DAV.DAV_UrshiPlugin", true);
			Hud.TryTogglePlugin("Razor.BountyDropTracker", true);
			Hud.TryTogglePlugin("Razor.Click.ClickEventHandler", true);
			Hud.TryTogglePlugin("Razor.CubedAndEmanatedItems", true);
			Hud.TryTogglePlugin("Razor.GreaterRiftHints", true);
			Hud.TryTogglePlugin("Razor.Hotkey.HotkeyEventHandler", true);
			Hud.TryTogglePlugin("Razor.ImmunityHelper", true);
			Hud.TryTogglePlugin("Razor.InventoryStashSearch", true);
			Hud.TryTogglePlugin("Razor.Label.LabelController", true);
			Hud.TryTogglePlugin("Razor.Log.TextLogger", true);
			Hud.TryTogglePlugin("Razor.MageGauge", true);
			Hud.TryTogglePlugin("Razor.Menu.MenuPlugin", true);
			Hud.TryTogglePlugin("Razor.MonsterCounter", true);
			Hud.TryTogglePlugin("Razor.Movable.MovableController", true);
			Hud.TryTogglePlugin("Razor.MovableBuffList", true);
			Hud.TryTogglePlugin("Razor.Party.PartyCOE", true);
			Hud.TryTogglePlugin("Razor.Proc.PartyProcScreenshots", false);
			Hud.TryTogglePlugin("Razor.Proc.PartyProcTracker", true);
			Hud.TryTogglePlugin("Razor.SkillCooldowns", true);
			Hud.TryTogglePlugin("Razor.SpiritBarrageHelper", true);
			Hud.TryTogglePlugin("Razor.Util.LocationInfo", false);
			Hud.TryTogglePlugin("Razor.Util.UIOverlapHelper", true);
			Hud.TryTogglePlugin("Resu.BattleTagAboveBanner", true);
			Hud.TryTogglePlugin("Resu.DangerPlugin", true);
			Hud.TryTogglePlugin("Resu.DarkerDiablo3Plugin", false);
			Hud.TryTogglePlugin("Resu.GroupGRLevelAdviserPlugin", true);
			Hud.TryTogglePlugin("Resu.HotEnablerDisablerPlugin", true);
			Hud.TryTogglePlugin("Resu.ParagonPercentagePlugin", true);
			Hud.TryTogglePlugin("Resu.UrshisGiftPlugin", true);
			Hud.TryTogglePlugin("User.CustomPluginEnablerOrDisabler", true);
			Hud.TryTogglePlugin("User.MenuPluginConfig", true);
			Hud.TryTogglePlugin("User.MovablePluginConfig", true);
			Hud.TryTogglePlugin("User.PluginEnablerOrDisablerPlugin", true);

		}
	}
}